module.exports = {
  ROLES: {
    USER: 'user',
    HOST: 'host',
    ADMIN: 'admin',
  },
  BOOKING_STATUS: {
    PENDING: 'pending',
    CONFIRMED: 'confirmed',
    CANCELLED: 'cancelled',
    COMPLETED: 'completed',
  },
  PROPERTY_TYPE: {
    APARTMENT: 'apartment',
    HOUSE: 'house',
    HOTEL: 'hotel',
    VILLA: 'villa',
    COTTAGE: 'cottage',
    CABIN: 'cabin',
    TREEHOUSE: 'treehouse',
    CASTLE: 'castle',
    TENT: 'tent',
    OTHER: 'other',
  },
  HTTP_STATUS: {
    OK: 200,
    CREATED: 201,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    CONFLICT: 409,
    UNPROCESSABLE_ENTITY: 422,
    INTERNAL_SERVER_ERROR: 500,
  },
  MESSAGES: {
    SUCCESS: 'Success',
    REGISTER_SUCCESS: 'User registered successfully',
    LOGIN_SUCCESS: 'Login successful',
    LOGOUT_SUCCESS: 'Logged out successfully',
    TOKEN_REFRESHED: 'Token refreshed successfully',
    PROFILE_FETCHED: 'Profile fetched successfully',
    PROFILE_UPDATED: 'Profile updated successfully',
    AVATAR_UPDATED: 'Avatar updated successfully',
    PASSWORD_CHANGED: 'Password changed successfully',
    FORGOT_PASSWORD_EMAIL_SENT: 'Password reset email sent',
    PASSWORD_RESET_SUCCESS: 'Password has been reset successfully',
    INVALID_CREDENTIALS: 'Invalid email or password',
    USER_NOT_FOUND: 'User not found',
    USER_ALREADY_EXISTS: 'User with this email already exists',
    UNAUTHORIZED: 'Unauthorized access',
    FORBIDDEN: 'You do not have permission to perform this action',
    TOKEN_EXPIRED: 'Token has expired',
    INVALID_TOKEN: 'Invalid token',
    SERVER_ERROR: 'Internal server error',
    VALIDATION_ERROR: 'Validation error',
    // Property
    PROPERTY_CREATED: 'Property created successfully',
    PROPERTY_UPDATED: 'Property updated successfully',
    PROPERTY_DELETED: 'Property deleted successfully',
    PROPERTY_NOT_FOUND: 'Property not found',
    PROPERTY_FETCHED: 'Property fetched successfully',
    PROPERTIES_FETCHED: 'Properties fetched successfully',
    FEATURED_PROPERTIES_FETCHED: 'Featured properties fetched successfully',
    // Category
    CATEGORIES_FETCHED: 'Categories fetched successfully',
    CATEGORY_NOT_FOUND: 'Category not found',
    // Search
    SEARCH_RESULTS_FETCHED: 'Search results fetched successfully',
    SUGGESTIONS_FETCHED: 'Suggestions fetched successfully',
    // Booking
    BOOKING_CREATED: 'Booking created successfully',
    BOOKING_CONFIRMED: 'Booking confirmed successfully',
    BOOKING_CANCELLED: 'Booking cancelled successfully',
    BOOKING_NOT_FOUND: 'Booking not found',
    BOOKINGS_FETCHED: 'Bookings fetched successfully',
    BOOKING_FETCHED: 'Booking fetched successfully',
    PROPERTY_NOT_AVAILABLE: 'Property is not available for selected dates',
    CHECK_IN_CHECK_OUT_REQUIRED: 'Check-in and check-out dates are required',
    CHECK_OUT_AFTER_CHECK_IN: 'Check-out must be after check-in',
    // Review
    REVIEW_CREATED: 'Review submitted successfully',
    REVIEW_NOT_FOUND: 'Review not found',
    REVIEWS_FETCHED: 'Reviews fetched successfully',
    ALREADY_REVIEWED: 'You have already reviewed this property',
    CANNOT_REVIEW_UNBOOKED: 'You can only review properties you have stayed at',
    // Wishlist
    WISHLIST_CREATED: 'Wishlist created successfully',
    WISHLIST_UPDATED: 'Wishlist updated successfully',
    WISHLIST_DELETED: 'Wishlist deleted successfully',
    WISHLIST_NOT_FOUND: 'Wishlist not found',
    WISHLISTS_FETCHED: 'Wishlists fetched successfully',
    PROPERTY_ADDED_TO_WISHLIST: 'Property added to wishlist',
    PROPERTY_REMOVED_FROM_WISHLIST: 'Property removed from wishlist',
    ALREADY_IN_WISHLIST: 'Property already in this wishlist',
    // Conversation
    CONVERSATION_CREATED: 'Conversation started successfully',
    CONVERSATIONS_FETCHED: 'Conversations fetched successfully',
    CONVERSATION_NOT_FOUND: 'Conversation not found',
    // Message
    MESSAGE_SENT: 'Message sent successfully',
    MESSAGES_FETCHED: 'Messages fetched successfully',
    // Help
    FAQ_FETCHED: 'FAQs fetched successfully',
  },
};
